### ISSUE TITLE
Overall really minor issue and potentially one big one

### ISSUE THREAD

**Issue by farishkash** [kingmilo/teacozy#1]
Minor issue is title, clients and companies get angry when their name isn't exact The Tea Cozy.

Could be a major issue but that is up to you.

If you plan to show your github to any recruiter you may want to change your comments.

In the age of what is happening with Uber etc, you are going to scare some people off.

My personal opinion.

**Comment by kingmilo** [comment]
Good catch re. the title, can't believe I didn't pick that one up. 

100% correct regarding the comments, they are not professional at all. My reasoning there was that I imagined the CA team having to go through so many versions of the same site so I thought I'd make it a bit more interesting, even if it is risqué. 

Thanks for your feedback!

**Comment by kingmilo** [comment]
Fixed comments
