### ISSUE TITLE
Site is excellent.

### ISSUE THREAD

**Issue by farishkash** [kingmilo/teacozy#2]
I really don't have any complaints you did a great job matching the spec.

**Comment by kingmilo** [comment]
Really glad to read this as I spent a lot of time struggling with the layout, and while I learnt a lot while struggling I also realized my understanding of flexbox and CSS layout in general is nowhere near where I want it to be.

**Comment by farishkash** [comment]
This video came out 3 days ago and it is one of the best explanations I have watched on flexbox.

https://www.youtube.com/watch?v=Mkza0N8NiK4

**Comment by kingmilo** [comment]
It's very helpful - thank you!

**Comment by kingmilo** [comment]
Title fixed.
